import { Suspense } from "react";
import SharedArtifactComponent from "@/components/sharedartifactcomponent";

export const metadata = {
    title: "Artifact | Chatbot",
    description: "Generated by Poe"
};

export default async function SharedArtifactPage(
    props: {
        params: Promise<{ id: string }>;
    }
) {
    const params = await props.params;
    return (
        <div className="w-full h-full">
            <Suspense fallback={<div>Loading...</div>}>
                <SharedArtifactComponent id={params.id} />
            </Suspense>
        </div>
    );
}
